### PR TITLE
fix contents being duplicated for already open files

### LINKED ISSUE #11: Opening an XML resource that is already open duplicates the contents
If you open an XML resource that is already open (from a sublime-package file, but not yet saved as an override), it correctly switches to the open tab, but it duplicates the contents of the file.

Example with `Batch File/Comments.tmPreferences`:

0. `Preferences` -> `Browse Packages`
0. Ensure there is no `Batch File` folder (i.e. delete it if there is one)
0. Switch back to ST3
0. Open Command Palette
0. Type `PRV: O` and select `Package Resource Viewer: Open Resource`
0. Select `Batch File`
0. Select `Comments.tmPreferences`
0. Repeat the previous step. The XML is duplicated each time.

Tested on ST3 builds 3114 and 3118 on Linux and Windows.

### PR DESCRIPTION
**Pull request by keith-hall**
fixes #11

### CODE REVIEW

**Comment by keith-hall** [comment]
this PR changes it so that if the file is already open (even if it doesn't exist yet because it hasn't been saved), it will switch to it, rather than appending the contents of the file from the sublime-package again.

**Comment by skuroda** [comment]
Thanks Keith, I've been really busy lately so haven't had time to put into looking into the bugs reported.  I'll take a look/merge this over the weekend.

**Comment by skuroda** [comment]
Looks good overall. The only thing that jumps stands out to me is the ST3 method call.  I'll take care of the ST2 implementation, and merge everything in.

**Comment by keith-hall** [comment]
ah I didn't think of checking if that method was available in ST2, sorry! Thanks Scott :)

**Comment by keith-hall** [comment]
I just had a look at your latest commit. Please note that at the moment, it is still always using the ST3 API, and not your new method which will handle ST2: https://github.com/skuroda/PackageResourceViewer/blob/ca23455d7033ee7f92bd7b098bc58edd76a3e375/package_resource_viewer.py#L131

BTW, thanks for all your hard work on this package - I use and recommend it all the time on the ST forums and SO :)

**Comment by skuroda** [comment]
Well, guess that's what happens when you don't double check the diffs. Oddly enough, even with your code it still returns `None`, so everything works out. That was a bit unexpected, but perhaps I'm a bit out of touch with non existent methods are handled in Python (or maybe something special for the ST objects).

**Pull request merged**
